import { Sparkles, UserRound } from 'lucide-react'
import type { Note } from '@/api/client'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'

type Provenance = Note['provenance']

/** Also names a cited note in chat ("N1 · You · BERT p.4"). */
export const PROVENANCE_LABEL: Record<Provenance, string> = {
  human: 'You',
  llm: 'AI',
  llm_edited: 'AI · edited',
}

const DESCRIPTION: Record<Provenance, string> = {
  human: 'Written by you',
  llm: 'Generated by a model. Verify before citing.',
  llm_edited: 'Generated by a model, then edited by you. Verify before citing.',
}

export function ProvenanceBadge({ provenance }: { provenance: Provenance }) {
  const human = provenance === 'human'
  return (
    // An icon as well as a colour, so provenance never depends on colour vision.
    <Badge
      variant={human ? 'secondary' : 'default'}
      className={cn('provenance-badge', !human && 'bg-provenance-llm text-provenance-llm-foreground')}
      title={DESCRIPTION[provenance]}
    >
      {human ? <UserRound aria-hidden /> : <Sparkles aria-hidden />}
      {PROVENANCE_LABEL[provenance]}
    </Badge>
  )
}
