# Generated by scripts/homebrew-casks from the v0.1.2 release. Don't edit by hand.
cask "paperlab@0.1.2" do
  arch arm: "arm64", intel: "x64"

  version "0.1.2"
  sha256 arm:   "152e42d0a874b702fb4642c9412933d4b351034ecc1c1ac43f4e82dd256985c2",
         intel: "b70bde96d816ca809123712e124722496c4e390889a792df447cedde023d400a"

  url "https://github.com/khannoussi-malek/PaperLab/releases/download/v#{version}/PaperLab-#{version}-#{arch}.dmg"
  name "PaperLab"
  desc "Local-first research reader for your papers"
  homepage "https://github.com/khannoussi-malek/PaperLab"

  depends_on :macos

  app "PaperLab.app"

  # PaperLab is ad-hoc signed, not notarized: clear the quarantine flag so macOS opens it without Open Anyway.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/PaperLab.app"]
  end

  caveats "PaperLab runs on Docker: install Docker Desktop (brew install --cask docker-desktop) and open it once."
end
