# Generated by scripts/homebrew-casks from the v0.1.0 release. Don't edit by hand.
cask "paperlab@0.1.0" do
  arch arm: "arm64", intel: "x64"

  version "0.1.0"
  sha256 arm:   "627037a1a662b69a552c44bfea74e8832159e530ead92058df29a30610232559",
         intel: "8f2e980193c04f54f436c5742eea51867d0d11f05e7395602d486348cf5c162d"

  url "https://github.com/khannoussi-malek/PaperLab/releases/download/v#{version}/PaperLab-#{version}-#{arch}.dmg"
  name "PaperLab"
  desc "Local-first research reader for your papers"
  homepage "https://github.com/khannoussi-malek/PaperLab"

  depends_on :macos

  app "PaperLab.app"

  # PaperLab is ad-hoc signed, not notarized: clear the quarantine flag so macOS opens it without Open Anyway.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/PaperLab.app"]
  end

  caveats "PaperLab runs on Docker: install Docker Desktop (brew install --cask docker-desktop) and open it once."
end
