import pytest

from tests.screening_pool import make_pool

pytestmark = pytest.mark.anyio

RANKED = (
    "Screening order was prioritised with active learning (naive Bayes over TF-IDF, retrained after each decision; "
    "PaperLab). All decisions were made by the reviewer."
)


async def _prisma(client, workspace):
    return (await client.get(f"/api/workspaces/{workspace.id}/search/prisma")).json()


async def test_no_automation_and_no_criteria_by_default(client, session):
    workspace, _ = await make_pool(session, [("x", None)])
    body = await _prisma(client, workspace)
    assert (body["automation"], body["screening_criteria"]) == ([], None)


async def test_ranked_use_and_criteria_are_reported(client, session):
    workspace, _ = await make_pool(session, [("x", None)])
    workspace.screening_ranked_used = True
    workspace.screening_criteria = "RCTs on sleep in adults"
    await session.flush()
    body = await _prisma(client, workspace)
    assert body["automation"] == [RANKED]
    assert body["screening_criteria"] == "RCTs on sleep in adults"


async def test_suggestion_models_are_named_once_each(client, session):
    workspace, hits = await make_pool(session, [("a", None), ("b", None), ("c", None)])
    hits[0].suggestion_model = hits[1].suggestion_model = "Ollama · qwen3:8b"
    await session.flush()
    body = await _prisma(client, workspace)
    assert body["automation"] == [
        "Title/abstract suggestions were generated by Ollama · qwen3:8b against the stated criteria; "
        "every decision was made by the reviewer."
    ]
